spring:
  datasource:
    url:  jdbc:mysql://192.168.2.131:3306/contacts-sync?useSSL=true&useUnicode=true&characterEncoding=UTF-8&socketTimeout=20000&connectTimeout=20000
    username: root
    password: 930825
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*Mapper.xml
server:
  port: 80
session:
  timeout:  30
  timeoutUnit:  DAYS